#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

export TEST_PLAN="${TEST_PLAN:-$ROOT_DIR/scripts/jmeter/async-order-open-loop.jmx}"
export DATA_FILE="${DATA_FILE:-/tmp/async-order-users-formal.csv}"
export REPORT_ROOT="${REPORT_ROOT:-$ROOT_DIR/reports/jmeter-soldout-flood}"
export HEAP="${HEAP:--Xms512m -Xmx2g -XX:MaxMetaspaceSize=256m}"
export POLL_RESULT=false

REQUESTS="${REQUESTS:-1000}"
STOCK_QUANTITY="${STOCK_QUANTITY:-600}"
ORDER_QUANTITY="${ORDER_QUANTITY:-1}"
export DURATION_SECONDS="${DURATION_SECONDS:-20}"
export TARGET_QPS="${TARGET_QPS:-$(((REQUESTS + DURATION_SECONDS - 1) / DURATION_SECONDS))}"
export THREADS="${THREADS:-100}"
export RAMP_SECONDS="${RAMP_SECONDS:-1}"

EXPECTED_SUCCESS_ORDERS=$((STOCK_QUANTITY / ORDER_QUANTITY))
EXPECTED_REQUESTS=$((TARGET_QPS * DURATION_SECONDS))

cat <<CONFIG
Mock-Damai Flash-Sale Sold-Out Flood
STOCK_QUANTITY=$STOCK_QUANTITY
ORDER_QUANTITY=$ORDER_QUANTITY
EXPECTED_SUCCESS_ORDERS<=$EXPECTED_SUCCESS_ORDERS
REQUESTS=$REQUESTS
TARGET_QPS=$TARGET_QPS
DURATION_SECONDS=$DURATION_SECONDS
THREADS=$THREADS
POLL_RESULT=$POLL_RESULT
DATA_FILE=$DATA_FILE
消息主链路=RocketMQ Transaction Message
CONFIG

if [[ "$EXPECTED_REQUESTS" -ne "$REQUESTS" ]]; then
  echo "注意：TARGET_QPS × DURATION_SECONDS = $EXPECTED_REQUESTS，不是精确 $REQUESTS。"
fi

exec "$ROOT_DIR/scripts/load/run-async-order-jmeter.sh"
